# Generated by Django 3.2.5 on 2021-08-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20210814_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='bond_list',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bonds',
        ),
        migrations.AddField(
            model_name='bond',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='character.character'),
        ),
        migrations.AddField(
            model_name='bond',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='BondList',
        ),
    ]
