# Generated by Django 3.2.5 on 2021-08-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20210815_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.AddField(
            model_name='character',
            name='hit_die',
            field=models.CharField(blank=True, choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12'), ('d20', 'd20')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.PositiveIntegerField(default=0, help_text="Equal to dex mod unless you have a feat or similar. If you're not sure, it's your dex mod."),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_heavy_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_light_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_martial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_medium_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_shields',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_simple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(default=0, help_text='Usually comes from your race'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='hit_die',
            field=models.CharField(blank=True, choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12'), ('d20', 'd20')], max_length=3, null=True),
        ),
    ]
