# Generated by Django 3.2.5 on 2021-08-18 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_auto_20210815_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficient', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('related_ability', models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], max_length=12)),
                ('custom', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='featuresandtraits',
            name='character',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='character',
        ),
        migrations.RemoveField(
            model_name='ideal',
            name='character',
        ),
        migrations.RemoveField(
            model_name='personalitytrait',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='procicient_charisma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_constitution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_dexterity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_intelligence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_strength',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_wisdom',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Bond',
        ),
        migrations.DeleteModel(
            name='FeaturesAndTraits',
        ),
        migrations.DeleteModel(
            name='Flaw',
        ),
        migrations.DeleteModel(
            name='Ideal',
        ),
        migrations.DeleteModel(
            name='PersonalityTrait',
        ),
        migrations.AddField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.character'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(through='character.CharacterSkill', to='character.Skill'),
        ),
    ]
