# Generated by Django 3.2.5 on 2021-08-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0015_auto_20210818_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('custom', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, to='character.Feat'),
        ),
    ]
