# Generated by Django 3.2.5 on 2021-08-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_auto_20210820_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_languages',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_tools',
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_languages',
            field=models.ManyToManyField(blank=True, to='character.Language'),
        ),
        migrations.AddField(
            model_name='character',
            name='proficient_tools',
            field=models.ManyToManyField(blank=True, to='character.Tool'),
        ),
    ]
