# Generated by Django 3.2.5 on 2021-08-20 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
        ('character', '0018_auto_20210820_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment_from_initial_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.equipmentfrominitialclass'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.skill'),
        ),
        migrations.AlterField(
            model_name='classandlevel',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characterclass'),
        ),
        migrations.AlterField(
            model_name='equipmentfrominitialclass',
            name='initial_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.characterclass'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inventoryarmor',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.armor'),
        ),
        migrations.AlterField(
            model_name='inventoryequipment',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='inventoryweapon',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.weapon'),
        ),
        migrations.AlterField(
            model_name='nametextcharacterfield',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
        migrations.AddField(
            model_name='language',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.script'),
        ),
    ]
