# Generated by Django 3.2.5 on 2021-08-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0026_auto_20210825_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='proficiency_needed',
            field=models.CharField(choices=[], default='', max_length=8),
        ),
    ]
