# Generated by Django 4.0.3 on 2022-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_artifact_thumbnail_id_alter_item_thumbnail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='markdown_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='markdown_notes',
            field=models.TextField(default=''),
        ),
    ]
