# Generated by Django 4.0.1 on 2022-01-31 03:33

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_initial'),
        ('item', '0002_armor_ac_bonus_equipment_brief_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('is_artifact', models.BooleanField(default=False, help_text='Defines whether this is a unique item.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_bonus', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='item.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.AddField(
            model_name='equipmenttraits',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='item.item'),
        ),
        migrations.AddField(
            model_name='armortraits',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='item.item'),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Armor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('item.item',),
        ),
    ]
