# Generated by Django 4.0.1 on 2022-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_artifacttraits_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armortraits',
            name='ac_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='artifacttraits',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='equipmenttraits',
            name='brief_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='weapontraits',
            name='attack_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
