# Generated by Django 4.1.7 on 2023-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0011_alias_is_primary"),
        ("item", "0009_artifact_aliases_item_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="aliases",
            field=models.ManyToManyField(
                blank=True, related_name="base_%(class)ss", to="nucleus.alias"
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="logs",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="nucleus.gamelog"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="aliases",
            field=models.ManyToManyField(
                blank=True, related_name="base_%(class)ss", to="nucleus.alias"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="logs",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="nucleus.gamelog"
            ),
        ),
    ]
