# Generated by Django 4.1.7 on 2023-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0013_place_related_places_place_related_races"),
        (
            "character",
            "0014_character_related_characters_character_related_items_and_more",
        ),
        ("race", "0010_race_related_races"),
        ("item", "0010_alter_artifact_aliases_alter_artifact_logs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="related_artifacts",
            field=models.ManyToManyField(blank=True, to="item.artifact"),
        ),
        migrations.AddField(
            model_name="artifact",
            name="related_characters",
            field=models.ManyToManyField(
                blank=True, related_name="related_artifacts", to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="related_items",
            field=models.ManyToManyField(
                blank=True, related_name="related_artifacts", to="item.item"
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="related_places",
            field=models.ManyToManyField(
                blank=True, related_name="related_artifacts", to="place.place"
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="related_races",
            field=models.ManyToManyField(
                blank=True, related_name="related_artifacts", to="race.race"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="related_items",
            field=models.ManyToManyField(blank=True, to="item.item"),
        ),
        migrations.AddField(
            model_name="item",
            name="related_places",
            field=models.ManyToManyField(
                blank=True, related_name="related_items", to="place.place"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="related_races",
            field=models.ManyToManyField(
                blank=True, related_name="related_items", to="race.race"
            ),
        ),
    ]
