databases:
    - name: prod
      databaseName: prod_dnd
      user: scottbowles

services:
    - type: web
      name: airel
      env: python
      buildCommand: "./build.sh"
      startCommand: "gunicorn website.wsgi:application"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: prod
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
