# Generated by Django 4.1a1 on 2022-06-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
            ],
        ),
    ]
