# Generated by Django 4.1a1 on 2022-06-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_npc_logs"),
        ("association", "0007_association_logs"),
        ("race", "0007_race_logs"),
        ("item", "0007_artifact_logs_item_logs"),
        ("place", "0009_export_logs_place_logs"),
        ("nucleus", "0002_entitylog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EntityLog",
            new_name="GameLog",
        ),
    ]
