# Generated by Django 4.1a1 on 2022-06-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleus", "0003_rename_entitylog_gamelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamelog",
            name="name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
