# Generated by Django 4.1.7 on 2023-04-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0005_user_last_activity_alter_gamelog_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelog",
            name="url",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
