# Generated by Django 4.1.7 on 2023-05-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0006_alter_gamelog_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="game_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamelog",
            name="google_created_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamelog",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
