# Generated by Django 4.1.7 on 2023-05-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0010_alter_place_place_type"),
        ("nucleus", "0007_gamelog_game_date_gamelog_google_created_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamelog",
            old_name="summary",
            new_name="brief",
        ),
        migrations.RenameField(
            model_name="gamelog",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="gamelog",
            name="places_set_in",
            field=models.ManyToManyField(
                blank=True, related_name="logs_set_in", to="place.place"
            ),
        ),
        migrations.AddField(
            model_name="gamelog",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
