# Generated by Django 4.1.7 on 2023-05-13 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0008_rename_summary_gamelog_brief_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="lock_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamelog",
            name="lock_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_lock_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
