# Generated by Django 4.1.7 on 2023-05-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0009_gamelog_lock_time_gamelog_lock_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
