# Generated by Django 4.1.7 on 2023-05-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0010_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="alias",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
