# Generated by Django 4.1.7 on 2023-05-31 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0012_ailogsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailogsuggestion",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
