# Generated by Django 4.1.7 on 2023-06-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0013_ailogsuggestion_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
