# Generated by Django 4.1.7 on 2025-06-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0015_sessionaudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="audio_session_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes for this session's audio, used for transcription context.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gamelog",
            name="last_game_log",
            field=models.ForeignKey(
                blank=True,
                help_text="The previous game log (used for context in transcription).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_game_logs",
                to="nucleus.gamelog",
            ),
        ),
        migrations.AlterField(
            model_name="sessionaudio",
            name="transcription_status",
            field=models.CharField(
                choices=[
                    ("not_transcribed", "Not Transcribed"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="not_transcribed",
                max_length=20,
            ),
        ),
    ]
