# Generated by Django 4.1.7 on 2025-06-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0016_gamelog_audio_session_notes_gamelog_last_game_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="generated_log_text",
            field=models.TextField(
                blank=True,
                help_text="Narrative session log generated by LLM.",
                null=True,
            ),
        ),
    ]
