# Generated by Django 5.2.3 on 2025-07-26 21:19

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0017_gamelog_generated_log_text"),
    ]

    operations = [VectorExtension()]
