# Generated by Django 5.2.3 on 2025-07-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0018_auto_20250726_2119"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="session_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sequential session number for ordering and reference",
                null=True,
            ),
        ),
    ]
