# Generated by Django 5.2.3 on 2025-08-16 03:28

from django.db import migrations


def forwards(apps, schema_editor):
    Character = apps.get_model("character", "Character")
    Item = apps.get_model("item", "Item")
    Artifact = apps.get_model("item", "Artifact")
    Place = apps.get_model("place", "Place")
    Association = apps.get_model("association", "Association")
    Race = apps.get_model("race", "Race")
    Alias = apps.get_model("nucleus", "Alias")

    for model in [Character, Item, Artifact, Place, Association, Race]:
        for entity in model.objects.all():
            if entity.aliases.filter(is_primary=True).count() == 0:
                new_alias = Alias.objects.create(name=entity.name, is_primary=True)
                entity.aliases.add(new_alias)


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0019_gamelog_session_number"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
