# Generated by Django 5.2.3 on 2025-08-16 04:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0020_auto_20250816_0328"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alias",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="alias_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
