# Generated by Django 5.2.3 on 2025-08-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0021_alias_alias_name_trgm_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="full_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
