# Generated by Django 5.2.3 on 2025-08-18 03:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0022_gamelog_full_text"),
        ("place", "0013_place_related_places_place_related_races"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="full_text_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="gamelog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_text_search_vector"], name="gamelog_fulltext_idx"
            ),
        ),
    ]
