# Generated by Django 5.2.3 on 2025-08-18 03:11

from django.contrib.postgres.search import SearchVector
from django.db import migrations

from nucleus.gdrive import fetch_airel_file_text


def fill_gamelog_full_text_from_google(apps, schema_editor):
    GameLog = apps.get_model("nucleus", "GameLog")
    for log in GameLog.objects.all():
        if log.full_text is None or log.full_text.strip() == "":
            log.full_text = fetch_airel_file_text(log.google_id)
            log.save()
        log.full_text_search_vector = SearchVector("full_text", config="simple")
        log.save()


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0023_gamelog_full_text_search_vector_and_more"),
    ]

    operations = [
        migrations.RunPython(
            fill_gamelog_full_text_from_google, reverse_code=migrations.RunPython.noop
        ),
    ]
