# Generated by Django 5.2.3 on 2025-09-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0024_auto_20250818_0311"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pc_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
