# Generated by Django 5.2.3 on 2026-03-25 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0025_user_pc_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("LOGIN", "Login"),
                            ("TOKEN_REFRESH", "Token Refresh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=2048, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="nucleus_use_user_id_4a4430_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "timestamp"],
                        name="nucleus_use_activit_6994fa_idx",
                    ),
                ],
            },
        ),
    ]
