# Generated by Django 4.0.1 on 2022-01-31 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_rename_item_content_type_artifactitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactitem',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='artifact.artifact'),
        ),
    ]
