# Generated by Django 3.2.5 on 2021-08-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_flaw_ideal_personalitytrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('hit_die', models.CharField(choices=[('4', 'd4'), ('6', 'd6'), ('8', 'd8'), ('10', 'd10'), ('12', 'd12'), ('20', 'd20')], max_length=2)),
                ('skill_number', models.PositiveIntegerField(default=0)),
                ('multiclass_skill_number', models.PositiveIntegerField(default=0)),
                ('equipment_choices', models.TextField()),
                ('major_saving_throw', models.CharField(choices=[('DEX', 'dexterity'), ('CON', 'constitution'), ('WIS', 'wisdom')], max_length=3)),
                ('minor_saving_throw', models.CharField(choices=[('STR', 'strength'), ('INT', 'intelligence'), ('CHA', 'charisma')], max_length=3)),
                ('proficient_light_armor', models.BooleanField(default=False)),
                ('proficient_heavy_armor', models.BooleanField(default=False)),
                ('proficient_shields', models.BooleanField(default=False)),
                ('proficient_martial_weapons', models.BooleanField(default=False)),
                ('proficient_simple_weapons', models.BooleanField(default=False)),
                ('proficient_other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAndLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.characterclass')),
            ],
        ),
    ]
