# Generated by Django 3.2.5 on 2021-08-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_characterclass_classandlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name_plural': 'character classes'},
        ),
        migrations.AlterModelOptions(
            name='classandlevel',
            options={'verbose_name_plural': 'classes and levels'},
        ),
        migrations.CreateModel(
            name='EquipmentFromInitialClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characterclass')),
            ],
            options={
                'verbose_name_plural': 'equipment from initial class',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='equipment_from_initial_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='character.equipmentfrominitialclass'),
        ),
    ]
