# Generated by Django 3.2.5 on 2021-08-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_auto_20210815_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.PositiveIntegerField(default=10, help_text='10 + dex mod + bonuses from armor, shields, spells, natural ac, class abilities, feats, magical items, etc.'),
        ),
        migrations.AddField(
            model_name='character',
            name='num_hit_dice',
            field=models.PositiveIntegerField(default=1, help_text='Almost certainly the same as your character level'),
        ),
        migrations.AddField(
            model_name='character',
            name='player_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='FeaturesAndTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('text', models.TextField(default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
