# Generated by Django 3.2.5 on 2021-08-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('character', '0014_bond_featuresandtraits_flaw_ideal_nametextcharacterfield_personalitytrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryWeapon',
            fields=[
                ('inventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.inventoryitem')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.weapon')),
            ],
            bases=('character.inventoryitem',),
        ),
        migrations.CreateModel(
            name='InventoryEquipment',
            fields=[
                ('inventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.inventoryitem')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment')),
            ],
            bases=('character.inventoryitem',),
        ),
        migrations.CreateModel(
            name='InventoryArmor',
            fields=[
                ('inventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.inventoryitem')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.armor')),
            ],
            bases=('character.inventoryitem',),
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, through='character.InventoryArmor', to='equipment.Armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(blank=True, through='character.InventoryEquipment', to='equipment.Equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, through='character.InventoryWeapon', to='equipment.Weapon'),
        ),
    ]
