# Generated by Django 3.2.5 on 2021-08-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_auto_20210818_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='procicient_charisma',
            new_name='proficient_charisma',
        ),
        migrations.AddField(
            model_name='character',
            name='passive_intelligence',
            field=models.PositiveIntegerField(default=10, help_text='10 + intelligence mod + bonuses (including investigation proficiency bonus)'),
        ),
        migrations.AddField(
            model_name='character',
            name='passive_wisdom',
            field=models.PositiveIntegerField(default=10, help_text='10 + wisdom mod + bonuses (including perception proficiency bonus)'),
        ),
    ]
