# Generated by Django 3.2.5 on 2021-08-24 13:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('character', '0024_bond_flaw_ideal_personalitytrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTool',
            fields=[
                ('inventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.inventoryitem')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.tool')),
            ],
            bases=('character.inventoryitem',),
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_bonus', models.IntegerField()),
                ('damage', models.CharField(max_length=100)),
                ('damage_type', models.CharField(default='', max_length=100)),
                ('range', models.CharField(default='', max_length=100)),
                ('properties', models.CharField(default='', max_length=100)),
                ('attack_ability_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default=list, max_length=12), size=None)),
                ('damage_ability_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default=list, max_length=12), size=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='tool',
            field=models.ManyToManyField(blank=True, through='character.InventoryTool', to='character.Tool'),
        ),
    ]
