# Generated by Django 3.2.7 on 2021-10-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0028_alter_attack_proficiency_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='proficiency_needed',
            field=models.ForeignKey(blank=True, help_text="E.g., 'martial weapons'. May have to create the needed proficiency.", limit_choices_to={'proficiency_type': 'weapon'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.proficiency'),
        ),
    ]
