# Generated by Django 3.2.8 on 2021-10-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0029_alter_attack_proficiency_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='features_and_traits',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.Feature'),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiencies',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.Proficiency'),
        ),
    ]
