# Generated by Django 4.0.3 on 2022-05-27 00:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_remove_association_image_id_association_image_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='image_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='association',
            name='markdown_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
