# Generated by Django 4.1.7 on 2023-05-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nucleus", "0010_alias"),
        ("association", "0007_association_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="aliases",
            field=models.ManyToManyField(
                blank=True, related_name="%(app_label)s_%(class)ss", to="nucleus.alias"
            ),
        ),
    ]
