# Generated by Django 4.1.7 on 2025-06-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nucleus", "0014_gamelog_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioTranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("character_name", models.CharField(max_length=100)),
                ("file_size_mb", models.FloatField()),
                ("duration_minutes", models.FloatField(blank=True, null=True)),
                ("transcript_text", models.TextField()),
                ("whisper_response", models.JSONField(default=dict)),
                ("was_split", models.BooleanField(default=False)),
                ("num_chunks", models.PositiveIntegerField(default=1)),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                ("campaign_context", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["character_name", "original_filename"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_sessions",
                        to="nucleus.gamelog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("chunk_number", models.PositiveIntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("start_time_offset", models.FloatField()),
                ("duration_seconds", models.FloatField()),
                ("chunk_text", models.TextField()),
                ("whisper_response", models.JSONField(default=dict)),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="transcription.audiotranscript",
                    ),
                ),
            ],
            options={
                "ordering": ["transcript", "chunk_number"],
            },
        ),
        migrations.AddField(
            model_name="audiotranscript",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripts",
                to="transcription.transcriptionsession",
            ),
        ),
    ]
