# Generated by Django 5.2.3 on 2025-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_remove_audiotranscript_session_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='audiotranscript',
            constraint=models.UniqueConstraint(
                fields=['session_audio'],
                name='unique_transcript_per_session_audio'
            ),
        ),
    ]