# Generated by Django 4.0.1 on 2022-01-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScoreIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_score', models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], max_length=12)),
                ('increase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_of_adulthood', models.PositiveIntegerField(blank=True, null=True)),
                ('life_expectency', models.PositiveIntegerField(blank=True, null=True)),
                ('alignment', models.CharField(blank=True, choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], max_length=2, null=True)),
                ('size', models.CharField(blank=True, choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan')], max_length=10, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
                ('ability_score_increases', models.ManyToManyField(blank=True, to='race.AbilityScoreIncrease')),
                ('base_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='race.race')),
                ('languages', models.ManyToManyField(blank=True, to='character.Language')),
                ('traits', models.ManyToManyField(blank=True, to='race.Trait')),
            ],
        ),
    ]
