# Generated by Django 4.0.2 on 2022-03-07 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_rename_life_expectency_race_life_expectancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='base_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='race.race'),
        ),
    ]
