# Generated by Django 4.0.2 on 2022-03-21 03:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('race', '0001_initial'),
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='image ids')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='image ids')),
                ('place_type', models.CharField(choices=[('STAR', 'Star'), ('PLANET', 'Planet'), ('MOON', 'Moon'), ('REGION', 'Region'), ('TOWN', 'Town'), ('DISTRICT', 'District'), ('LOCATION', 'Location')], default='LOCATION', max_length=8)),
                ('population', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('notes', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significance', models.IntegerField(choices=[(0, 'Major'), (1, 'Minor')], default=0)),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.export')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
            options={
                'unique_together': {('place', 'export')},
            },
        ),
        migrations.CreateModel(
            name='PlaceAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='associations',
            field=models.ManyToManyField(through='place.PlaceAssociation', to='association.Association'),
        ),
        migrations.AddField(
            model_name='place',
            name='common_races',
            field=models.ManyToManyField(through='place.PlaceRace', to='race.Race'),
        ),
        migrations.AddField(
            model_name='place',
            name='exports',
            field=models.ManyToManyField(through='place.PlaceExport', to='place.Export'),
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='place.place'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
    ]
