# Generated by Django 4.0.1 on 2022-01-29 02:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import place.models.place


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('race', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=0)),
                ('associations', models.ManyToManyField(through='place.PlaceAssociation', to='association.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('parent', models.PositiveSmallIntegerField(blank=True, default=None, editable=False, null=True, validators=[place.models.place.validate_none])),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('parent_object_id', models.PositiveIntegerField()),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails')),
                ('parent_content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'place'), ('model__in', ['planet', 'region'])), on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_parent', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.planet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('notes', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significance', models.IntegerField(choices=[(0, 'Major'), (1, 'Minor')], default=0)),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.export')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails')),
            ],
        ),
        migrations.AddField(
            model_name='placedetails',
            name='common_races',
            field=models.ManyToManyField(through='place.PlaceRace', to='race.Race'),
        ),
        migrations.AddField(
            model_name='placedetails',
            name='exports',
            field=models.ManyToManyField(through='place.PlaceExport', to='place.Export'),
        ),
        migrations.AddField(
            model_name='placeassociation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('parent_object_id', models.PositiveIntegerField()),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails')),
                ('parent_content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'place'), ('model__in', ['planet', 'region', 'town', 'district'])), on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_parent', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('parent_object_id', models.PositiveIntegerField()),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.placedetails')),
                ('parent_content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'place'), ('model__in', ['planet', 'region', 'town'])), on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_parent', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
