# Generated by Django 4.0.2 on 2022-02-17 04:34

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
        ('association', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('place_type', models.CharField(choices=[('star', 'Star'), ('planet', 'Planet'), ('moon', 'Moon'), ('region', 'Region'), ('town', 'Town'), ('district', 'District'), ('location', 'Location')], default='location', max_length=8)),
                ('population', models.IntegerField(default=0)),
                ('associations', models.ManyToManyField(through='place.PlaceAssociation', to='association.Association')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='details',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='placedetails',
            name='associations',
        ),
        migrations.RemoveField(
            model_name='placedetails',
            name='common_races',
        ),
        migrations.RemoveField(
            model_name='placedetails',
            name='exports',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='details',
        ),
        migrations.RemoveField(
            model_name='region',
            name='details',
        ),
        migrations.RemoveField(
            model_name='region',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='town',
            name='details',
        ),
        migrations.RemoveField(
            model_name='town',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='placerace',
            name='location',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Planet',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
        migrations.AddField(
            model_name='place',
            name='common_races',
            field=models.ManyToManyField(through='place.PlaceRace', to='race.Race'),
        ),
        migrations.AddField(
            model_name='place',
            name='exports',
            field=models.ManyToManyField(through='place.PlaceExport', to='place.Export'),
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='place.place'),
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.AddField(
            model_name='placerace',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeassociation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place'),
        ),
        migrations.AlterField(
            model_name='placeexport',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place'),
        ),
        migrations.DeleteModel(
            name='PlaceDetails',
        ),
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('place.place',),
        ),
    ]
