# Generated by Django 4.0.3 on 2022-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_export_thumbnail_id_alter_place_thumbnail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='markdown_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='markdown_notes',
            field=models.TextField(default=''),
        ),
    ]
