# Generated by Django 4.0.2 on 2022-03-10 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_place_place_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='place.place'),
        ),
    ]
