# Generated by Django 4.0.3 on 2022-04-24 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_export_lock_time_export_lock_user_place_lock_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image_id',
        ),
        migrations.AddField(
            model_name='export',
            name='image_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='image_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
