# Generated by Django 4.0.3 on 2022-05-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_export_image_ids_alter_export_markdown_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('STAR', 'Star'), ('PLANET', 'Planet'), ('MOON', 'Moon'), ('REGION', 'Region'), ('TOWN', 'Town'), ('DISTRICT', 'District'), ('LOCATION', 'Location')], max_length=8, null=True),
        ),
    ]
