# Generated by Django 4.0.3 on 2022-05-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_alter_place_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('Star', 'Star'), ('Planet', 'Planet'), ('Moon', 'Moon'), ('Region', 'Region'), ('Town', 'Town'), ('District', 'District'), ('Location', 'Location')], max_length=8, null=True),
        ),
    ]
