# Generated by Django 4.1a1 on 2022-06-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleus", "0002_entitylog"),
        ("place", "0008_alter_place_place_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="logs",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)ss",
                to="nucleus.entitylog",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="logs",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)ss",
                to="nucleus.entitylog",
            ),
        ),
    ]
