# Generated by Django 4.1.7 on 2023-04-25 04:47

from django.db import migrations
import django_choices_field.fields
import place.models.place


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0009_export_logs_place_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Star", "Star"),
                    ("Planet", "Planet"),
                    ("Moon", "Moon"),
                    ("Region", "Region"),
                    ("Town", "Town"),
                    ("District", "District"),
                    ("Location", "Location"),
                ],
                choices_enum=place.models.place.Place.PlaceType,
                max_length=8,
                null=True,
            ),
        ),
    ]
