# Generated by Django 4.0.2 on 2022-03-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_remove_location_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('STAR', 'Star'), ('PLANET', 'Planet'), ('MOON', 'Moon'), ('REGION', 'Region'), ('TOWN', 'Town'), ('DISTRICT', 'District'), ('LOCATION', 'Location')], default='LOCATION', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='placeexport',
            unique_together={('place', 'export')},
        ),
    ]
