# Generated by Django 5.2.3 on 2025-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="last_summarized_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last summarization", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Auto-generated conversation summary"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="summary_up_to_message_id",
            field=models.IntegerField(
                blank=True,
                help_text="Last message ID included in the summary",
                null=True,
            ),
        ),
    ]
