# Generated by Django 5.2.3 on 2025-08-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="included_in_summary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this message has been included in the conversation summary",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="conversation_summary",
            field=models.TextField(
                default="",
                help_text="Running summary of all messages outside the sliding token window",
            ),
        ),
    ]
