# Generated by Django 5.2.3 on 2025-08-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("rag_chat", "0002_chatmessage_included_in_summary_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contentchunk",
            new_name="rag_chat_co_content_4549bc_idx",
            old_name="rag_chat_co_content_ef93cc_idx",
        ),
        migrations.RenameIndex(
            model_name="contentchunk",
            new_name="rag_chat_co_content_6137b3_idx",
            old_name="rag_chat_co_content_9f83bf_idx",
        ),
        migrations.AlterField(
            model_name="contentchunk",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Content type for the generic foreign key",
                limit_choices_to={
                    "app_label__in": [
                        "character",
                        "place",
                        "item",
                        "race",
                        "association",
                        "nucleus",
                    ],
                    "model__in": [
                        "character",
                        "place",
                        "item",
                        "artifact",
                        "race",
                        "association",
                        "gamelog",
                    ],
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="contentchunk",
            name="object_id",
            field=models.PositiveBigIntegerField(
                help_text="ID of the source object (primary key of the related model)"
            ),
        ),
    ]
