# Generated by Django 5.2.3 on 2025-09-05 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rag_chat",
            "0003_rename_rag_chat_co_content_ef93cc_idx_rag_chat_co_content_4549bc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_send_chat_message", "Can send chat messages")],
            },
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("can_use_rag_chat", "Can use RAG chat"),
                    ("can_start_chat_session", "Can start new chat sessions"),
                ],
            },
        ),
    ]
