# Generated by Django 5.2.3 on 2026-03-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_chat", "0004_alter_chatmessage_options_alter_chatsession_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Archived sessions are hidden from the user"
            ),
        ),
    ]
