# Generated by Django 4.0.1 on 2022-01-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='tool',
            field=models.ManyToManyField(blank=True, through='character.InventoryTool', to='character.Tool'),
        ),
    ]
