# Generated by Django 4.0.3 on 2022-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_npc_thumbnail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='markdown_notes',
            field=models.TextField(default=''),
        ),
    ]
