# Generated by Django 4.0.2 on 2022-03-04 04:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
        ('character', '0004_alter_character_armor_alter_character_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan')], max_length=10, null=True)),
                ('features_and_traits', models.ManyToManyField(blank=True, related_name='npcs', to='character.Feature')),
                ('proficiencies', models.ManyToManyField(blank=True, related_name='npcs', to='character.Proficiency')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPCFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='character.npc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
