# Generated by Django 3.2.5 on 2021-08-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20210812_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('bond_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.bondlist')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='character.bondlist'),
        ),
    ]
