# Generated by Django 4.0.3 on 2022-05-27 00:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_alter_association_image_ids_and_more'),
        ('character', '0007_remove_npc_image_id_npc_image_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='associations',
            field=models.ManyToManyField(blank=True, related_name='npcs', to='association.association'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='image_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='npc',
            name='markdown_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
