# Generated by Django 4.1a1 on 2022-06-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleus", "0002_entitylog"),
        ("character", "0008_npc_associations_alter_npc_image_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="logs",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)ss",
                to="nucleus.entitylog",
            ),
        ),
    ]
