# Generated by Django 4.1.7 on 2023-04-12 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("race", "0007_race_logs"),
        ("nucleus", "0005_user_last_activity_alter_gamelog_google_id"),
        ("association", "0007_association_logs"),
        ("character", "0010_rename_character_playercharacter_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NPC",
            new_name="Character",
        ),
    ]
