# Generated by Django 3.2.5 on 2021-08-18 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_auto_20210818_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameTextCharacterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('text', models.TextField(default='')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('nametextcharacterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.nametextcharacterfield')),
            ],
            bases=('character.nametextcharacterfield',),
        ),
        migrations.CreateModel(
            name='FeaturesAndTraits',
            fields=[
                ('nametextcharacterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.nametextcharacterfield')),
            ],
            options={
                'verbose_name_plural': 'features and traits',
            },
            bases=('character.nametextcharacterfield',),
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('nametextcharacterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.nametextcharacterfield')),
            ],
            bases=('character.nametextcharacterfield',),
        ),
        migrations.CreateModel(
            name='Ideal',
            fields=[
                ('nametextcharacterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.nametextcharacterfield')),
            ],
            bases=('character.nametextcharacterfield',),
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('nametextcharacterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.nametextcharacterfield')),
            ],
            bases=('character.nametextcharacterfield',),
        ),
    ]
