# Generated by Django 4.1.7 on 2023-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0013_place_related_places_place_related_races"),
        ("race", "0010_race_related_races"),
        ("item", "0010_alter_artifact_aliases_alter_artifact_logs_and_more"),
        ("character", "0013_alter_character_aliases_alter_character_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="related_characters",
            field=models.ManyToManyField(blank=True, to="character.character"),
        ),
        migrations.AddField(
            model_name="character",
            name="related_items",
            field=models.ManyToManyField(
                blank=True, related_name="related_characters", to="item.item"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="related_places",
            field=models.ManyToManyField(
                blank=True, related_name="related_characters", to="place.place"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="related_races",
            field=models.ManyToManyField(
                blank=True, related_name="related_characters", to="race.race"
            ),
        ),
    ]
