# Generated by Django 3.2.5 on 2021-08-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0019_auto_20210820_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.CharField(blank=True, choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan')], max_length=10, null=True),
        ),
    ]
