# Generated by Django 3.2.5 on 2021-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0020_character_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('equipment_options', models.TextField()),
                ('suggested_characteristics', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='background',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.DeleteModel(
            name='FeaturesAndTraits',
        ),
        migrations.AddField(
            model_name='background',
            name='features',
            field=models.ManyToManyField(related_name='backgrounds', to='character.Feature'),
        ),
        migrations.AddField(
            model_name='background',
            name='languages',
            field=models.ManyToManyField(related_name='backgrounds', to='character.Language'),
        ),
        migrations.AddField(
            model_name='background',
            name='skill_proficiencies',
            field=models.ManyToManyField(related_name='backgrounds', to='character.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='features_and_traits',
            field=models.ManyToManyField(related_name='characters', to='character.Feature'),
        ),
    ]
