# Generated by Django 3.2.5 on 2021-08-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0022_auto_20210820_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proficiency_type', models.CharField(choices=[('armor', 'Armor'), ('weapon', 'Weapon'), ('skill', 'Skill'), ('tool', 'Tool'), ('language', 'Language'), ('ability', 'Ability'), ('other', 'Other')], default='other', max_length=8)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Proficiencies',
            },
        ),
        migrations.RemoveField(
            model_name='characterskill',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='equipmentfrominitialclass',
            name='initial_class',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='nametextcharacterfield_ptr',
        ),
        migrations.RemoveField(
            model_name='ideal',
            name='nametextcharacterfield_ptr',
        ),
        migrations.RemoveField(
            model_name='nametextcharacterfield',
            name='character',
        ),
        migrations.RemoveField(
            model_name='personalitytrait',
            name='nametextcharacterfield_ptr',
        ),
        migrations.RemoveField(
            model_name='character',
            name='equipment_from_initial_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_heavy_armor',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_languages',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_light_armor',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_martial',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_medium_armor',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_other',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_shields',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_simple',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_tools',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_wisdom',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='proficient_heavy_armor',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='proficient_light_armor',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='proficient_martial_weapons',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='proficient_other',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='proficient_shields',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='proficient_simple_weapons',
        ),
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Bond',
        ),
        migrations.DeleteModel(
            name='CharacterSkill',
        ),
        migrations.DeleteModel(
            name='EquipmentFromInitialClass',
        ),
        migrations.DeleteModel(
            name='Flaw',
        ),
        migrations.DeleteModel(
            name='Ideal',
        ),
        migrations.DeleteModel(
            name='NameTextCharacterField',
        ),
        migrations.DeleteModel(
            name='PersonalityTrait',
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.UniqueConstraint(fields=('name', 'proficiency_type'), name='unique_proficiency'),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.ManyToManyField(related_name='characters', to='character.Proficiency'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='proficiencies',
            field=models.ManyToManyField(related_name='classes', to='character.Proficiency'),
        ),
    ]
