# Generated by Django 4.0.2 on 2022-03-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='life_expectency',
            new_name='life_expectancy',
        ),
        migrations.AlterField(
            model_name='abilityscoreincrease',
            name='ability_score',
            field=models.CharField(choices=[('STRENGTH', 'Strength'), ('DEXTERITY', 'Dexterity'), ('CONSTITUTION', 'Constitution'), ('INTELLIGENCE', 'Intelligence'), ('WISDOM', 'Wisdom'), ('CHARISMA', 'Charisma')], max_length=12),
        ),
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.CharField(blank=True, choices=[('TINY', 'Tiny'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('HUGE', 'Huge'), ('GARGANTUAN', 'Gargantuan')], max_length=10, null=True),
        ),
    ]
