# Generated by Django 4.0.2 on 2022-03-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_alter_abilityscoreincrease_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
