# Generated by Django 4.1.7 on 2023-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race", "0009_alter_race_aliases_alter_race_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="related_races",
            field=models.ManyToManyField(blank=True, to="race.race"),
        ),
    ]
