# Generated by Django 4.0.1 on 2022-01-31 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_armortraits_equipmenttraits_item_weapontraits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Artifact',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('item.item',),
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_artifact',
        ),
        migrations.CreateModel(
            name='ArtifactTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='item.item')),
            ],
        ),
    ]
